### ISSUE TITLE
Hi Marcello

### ISSUE THREAD

**Issue by bpvgoncalves** [mlarocca/mlarocca.github.com#1]
Hi Marcello.
I received your July 23rd post while I was doing the peer reviewing in the September course. I'd like to know if this is a valid submission from you (for example, you're retaking the course), or if someone else are using your work on their submission.

**Comment by mlarocca** [comment]
Hello Bruno,
nice to meet you, and thanks for getting in touch.
No, I'm not retaking the course, so I guess someone has found a nice shortcut.
I thought the assignment would change in different sessions, so I left it online; I guess I should probably remove it,  and we should probably inform the course staff about the violation to the honor code as well.

Thanks again for the heads-up!

**Comment by bpvgoncalves** [comment]
Hello again. 
Thank you very much for your quick answer. I will report this to the staff and I hope they will take some measures... this is not good for MOOC's image!

Thanks a lot once again... and, nice work (I hope you got good marks for it!!).
Regards.

**Comment by mlarocca** [comment]
Hi Bruno,
sorry for the delay!
Thanks again for pointing this out, and also thanks for the compliments :)

I hope your experience with the course was as good as mine - they are good courses, indeed - and you had no further inconvenience.

Cheers!
